name: your_project_name
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  geolocator: ^13.0.2
  jiffy: ^6.3.1
  http: ^1.2.2
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  firebase_auth: ^5.4.0
  firebase_storage: ^12.4.0
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.1.0
  image_picker: ^1.1.2
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.3.5
  camera: ^0.10.6
  sensors_plus: ^6.1.1
  heart_bpm: ^2.0.0+0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
